swagger: "2.0"
info:
  title: Donler API v1
  description: Donler API v1
  version: 1.0.0
host: "localhost:3002"
schemes:
  - http
produces:
  - application/json
  - text/plain
paths:
  /users/login:
    post:
      tags:
        - users
      summary: 用户登录
      operationId: login
      consumes:
        - application/json
      parameters:
        - name: body
          schema:
            $ref: LoginForm
          in: body
          required: true
          description: 登录邮箱和密码
        - name: X-Parse-Application-Id
          type: string
          in: header
          required: true
          description: app id
        - name: X-Parse-REST-API-Key
          type: string
          in: header
          required: true
          description: api key
        - name: X-Device-Id
          type: string
          in: header
          required: true
          description: 设备id
        - name: X-Device-Type
          type: string
          in: header
          required: true
          description: 设备型号
        - name: X-Platform
          type: string
          in: header
          required: true
          description: 平台系统
        - name: X-Version
          type: string
          in: header
          required: true
          description: 平台版本
      responses:
        "400":
          description: 邮箱格式不正确或未填写邮箱或密码
        "401":
          description: 邮箱或密码错误
        default:
          description: 登录成功后返回的数据
          schema:
            $ref: LoginSuccess
  "/users/{userId}":
    get:
      tags:
        - users
      summary: 获取用户数据
      operationId: getUserData
      parameters:
        - name: userId
          description: 用户id
          required: true
          type: string
          in: path
        - name: X-Access-Token
          type: string
          in: header
          required: true
          description: access token
      responses:
        "400":
          description: 缺少id
        "401":
          description: 未登录
        default:
          description: 用户数据
          schema:
            $ref: User
  /companies:
    post:
      tags:
        - companies
      summary: 注册公司账号(todo)
      operationId: addCompany
      consumes:
        - application/json
      produces:
        - text/plain
      responses:
        "405":
          description: Invalid input
  "/companies/{companyId}":
    get:
      tags:
        - companies
      summary: 获取公司信息
      responses:
        default:
          description: 公司数据
          schema:
            $ref: Company
      operationId: getCompany
      produces:
        - application/json
      parameters:
        - name: companyId
          description: 公司id
          required: true
          type: string
          in: path
  /campaigns:
    post:
      tags:
        - campaigns
      summary: 发起活动
      operationId: addCampaign
      parameters:
        - name: body
          description: Campaign object that needs to be added to the store
          required: true
          schema:
            $ref: Campaign
          in: body
      responses:
        "200":
          description: 发起成功
        "405":
          description: 无效输入
    get:
      tags:
        - campaigns
      summary: 获取活动列表
      operationId: getCampaign
      parameters:
        - name: hostType
          description: Campaign object that needs to be added to the store
          required: true
          type: string
          in: query
          enum:
            - user
            - team
            - company
        - name: hostId
          description: Campaign object that needs to be added to the store
          required: true
          type: string
          in: query
      responses:
        "200":
          description: 成功
        default:
          description: 默认返回
  "/campaigns/{campaignId}":
    get:
      tags:
        - campaigns
      summary: 获取单个活动
      operationId: getCampaignById
      parameters:
        - name: campaignId
          description: 活动 Id
          required: true
          type: string
          in: path
      responses:
        "200":
          description: 成功
        default:
          description: 默认返回
    patch:
      tags:
        - campaigns
      summary: 修改活动
      operationId: updateCampaign
      consumes:
        - application/json
      parameters:
        - name: campaignId
          description: 活动 Id
          required: true
          type: string
          in: path
        - name: body
          description: Campaign object that needs to be added to the store
          required: true
          schema:
            $ref: Campaign
          in: body
      responses:
        "200":
          description: 成功
        default:
          description: 默认返回
    delete:
      tags:
        - campaigns
      summary: 关闭活动
      operationId: closeCampaign
      consumes:
        - application/json
      parameters:
        - name: campaignId
          description: 活动 Id
          required: true
          type: string
          in: path
      responses:
        "200":
          description: 成功
        default:
          description: 默认返回
  "/campaigns/{campaignId}/users/{userId}":
    post:
      tags:
        - campaigns
      summary: 参加活动
      operationId: joinCampaign
      consumes:
        - application/json
      parameters:
        - name: campaignId
          description: 活动 Id
          required: true
          type: string
          in: path
        - name: userId
          description: 用户 Id
          required: true
          type: string
          in: path
      responses:
        "200":
          description: 成功
        default:
          description: 默认返回
    delete:
      tags:
        - campaigns
      summary: 退出活动
      operationId: quitCampaign
      consumes:
        - application/json
      parameters:
        - name: campaignId
          description: 活动 Id
          required: true
          type: string
          in: path
        - name: userId
          description: 用户 Id
          required: true
          type: string
          in: path
      responses:
        "200":
          description: 成功
        default:
          description: 默认返回
definitions:
  LoginForm:
    title: LoginForm
    type: object
    required:
      - email
      - password
    properties:
      email:
        description: 用户邮箱
        type: string
      password:
        description: 密码
        type: string
  LoginSuccess:
    title: LoginSuccess
    type: object
    required:
      - token
    properties:
      token:
        type: string
        description: "access token, 有效期7天"
  User:
    title: User
    type: object
    required:
      - email
    properties:
      email:
        type: string
        description: 用户邮箱
      nickname:
        type: string
        description: 昵称
      realname:
        type: string
        description: 真实姓名
      department:
        type: object
        description: 部门
        properties:
          _id:
            type: string
            description: 部门id
          name:
            type: string
            description: 部门名
      sex:
        type: string
        enum:
          - 男
          - 女
        description: 性别
      birthday:
        type: string
        format: date-time
        description: 生日
      bloodType:
        type: string
        description: 血型
      introduce:
        type: string
        description: 简介
      registerDate:
        type: string
        format: date-time
        description: 注册时间
      phone:
        type: string
        description: 电话号码
  RegisterForm:
    title: RegisterForm
    required:
      - name
    properties:
      name:
        description: 公司名称，与营业执照注册名保持一致
        type: string
      province:
        description: 省份
        type: string
      city:
        description: 城市
        type: string
      district:
        description: 区
        type: string
      address:
        description: 详细地址
        type: string
      contacts:
        description: 联系人
        type: string
  Company:
    title: Company
    required:
      - _id
      - name
      - short_name
      - logo
    properties:
      _id:
        description: 公司id
        type: string
      username:
        description: 企业账号登录用的用户名
        type: string
      domains:
        description: 邮箱后缀
        type: array
        items:
          type: string
      name:
        description: 公司名称
        type: string
      shortName:
        description: 公司简称
        type: string
      logo:
        description: 公司logo url
        type: string
      province:
        description: 省份
        type: string
      city:
        description: 城市
        type: string
      district:
        description: 区
        type: string
      address:
        description: 详细地址
        type: string
      contacts:
        description: 联系人
        type: string
      email:
        description: 公司邮箱
        type: string
      memberNumber:
        description: 公司成员数量
        type: integer
        format: int64
      companyInviteCodes:
        description: 可供其它企业注册时使用的邀请码
        type: array
        items:
          type: string
      staffInviteCode:
        description: 给该企业员工使用的邀请码
        type: string
  Campaign:
    title: Campaign
    required:
      - cid
      - theme
      - location
      - start_time
      - end_time
      - campaign_mold
    properties:
      cid:
        type: array
        description: 活动所属公司的id
        items:
          type: string
      tid:
        type: array
        description: 活动所属小队的id
        items:
          type: string
      campaign_unit:
        type: array
        description: 活动的阵营
        items:
          $ref: CampaignUnit
      theme:
        type: string
        description: 活动主题
      location:
        $ref: Location
      start_time:
        description: 活动开始时间
        type: string
        format: date-time
      end_time:
        description: 活动结束时间
        type: string
        format: date-time
      deadline:
        description: 报名截止时间
        type: string
        format: date-time
      campaign_mold:
        description: 活动类型
        type: string
      content:
        description: 活动内容
        type: string
      member_min:
        description: 报名人数下限
        type: integer
      member_max:
        description: 报名人数上限
        type: integer
      tags:
        description: 标签
        type: array
        items:
          type: string
  Location:
    title: Location
    required:
      - name
    properties:
      name:
        type: string
        description: 地点名称
      coordinate:
        type: array
        description: 地点坐标
        items:
          type: number
          format: double
  CampaignUnit:
    title: CampaignUnit
    properties:
      company:
        $ref: CompanyBrief
      team:
        $ref: TeamBrief
      member:
        type: array
        description: 参加的成员
        items:
          $ref: Member
      member_quit:
        type: array
        description: 退出的成员
        items:
          $ref: Member
  CompanyBrief:
    title: CompanyBrief
    required:
      - _id
    properties:
      _id:
        type: string
        description: 公司id
      name:
        type: string
        description: 公司名称
      logo:
        type: string
        description: 公司头像
  TeamBrief:
    title: TeamBrief
    required:
      - _id
    properties:
      _id:
        type: string
        description: 小队id
      name:
        type: string
        description: 小队名称
      logo:
        type: string
        description: 小队头像
  Member:
    title: Member
    required:
      - _id
    properties:
      _id:
        type: string
        description: 用户id
      nickname:
        type: string
        description: 用户昵称
      photo:
        type: string
        description: 用户头像
