swagger: "2.0"
info:
  title: Donler API v2
  description: Donler API v2
  version: 2.0.0
host: localhost:3002
basePath: /v2_0
schemes:
  - http
produces:
  - application/json
  - text/plain
paths:
  /users/login:
    post:
      tags:
        - users
      summary: 用户登录
      operationId: userLogin
      consumes:
        - application/json
      parameters:
        - name: body
          schema:
            $ref: LoginForm
          in: body
          required: true
          description: 登录邮箱和密码
      responses:
        default:
          description: error
          schema:
            $ref: Error
        "200":
          description: 登录成功后返回的数据
          schema:
            $ref: LoginSuccess
  /gifts/{userId}/{direction}:
    get:
      tags:
        - gifts
      summary: 获取当前用户收到/发出的礼物
      produces:
        - application/json
      parameters:
        - name: userId
          description: 用户id
          required: true
          type: string
          in: path
          default: 53aa707a11fd597b3e1be260
        - name: direction
          description: 收到/发出
          required: true
          type: string
          in: path
          enum:
            - send
            - receive
          default: send
        - name: lastTime
          description: 上一条时间,若无则取最新
          required: false
          type: date-time
          in: query
        - name: limit
          description: 一次取几条
          required: false
          type: number
          in: query
      responses:
        "200":
          description: 获取的礼物
          schema:
            type: array
            items:
              $ref: Gift
        default:
          description: error
          schema:
            $ref: Error
  /gifts:
    post:
      tags:
        - gifts
      summary: 送礼
      produces:
        - application/json
      parameters:
        - name: body
          schema:
            $ref: PostGift
          in: body
          required: true
          description: 礼物所需body
      responses:
        "200":
          description: 成功
          schema:
            $ref: GiftResponse
        default:
          description: error
          schema:
            $ref: Error
  /gifts/{giftId}:
    get:
      tags:
        - gifts
      summary: 获取某礼物详情
      produces:
        - application/json
      parameters:
        - name: giftId
          description: 礼物id
          required: true
          type: string
          in: path
      responses:
        "200":
          description: 成功
          schema:
            $ref: GiftResponse
        default:
          description: error
          schema:
            $ref: Error
  "/interaction/{interactionType}":
    post:
      tags:
        - interaction
      summary: 发互动
      operationId: postInteraction
      consumes:
        - application/json
      parameters:
        - name: interactionType
          description: 互动类型
          required: true
          type: string
          in: path
          enum:
            - activity
            - poll
            - question
        - name: body
          description: 求助信息
          required: true
          schema:
            $ref: QuestionForm
          in: body
      responses:
        200:
          description: 成功
          schema:
           $ref: InteractionForm
        default:
          description: error
          schema:
            $ref: Error
    get:
      tags:
        - interaction
      summary: 获取互动列表
      operationId: getQuestion
      consumes:
        - application/json
      parameters:
        - name: interactionType
          description: 互动类型
          required: true
          type: string
          in: path
          enum:
            - activity
            - poll
            - question
            - all
      responses:
        "200":
          description: 成功
          schema:
            type: array
            items:
              $ref: InteractionForm
        default:
          description: error
          schema:
            $ref: Error
  "/interaction/{interactionType}/{interactionId}":
    get:
      tags:
        - interaction
      summary: 获取互动详情
      operationId: getInteractionDetail
      consumes:
        - application/json
      parameters:
        - name: interactionType
          description: 互动类型
          required: true
          type: string
          in: path
          enum:
            - activity
            - poll
            - question
        - name: interactionId
          description: 互动id
          required: true
          type: string
          in: path
      responses:
        "200":
          description: 成功
          schema:
            type: array
            items:
              $ref: InteractionForm
        default:
          description: error
          schema:
            $ref: Error
  "/interaction/poll/{interactionId}/users/{userId}":
    post:
      tags:
        - interaction
      summary: 进行投票
      operationId: poll
      consumes:
        - application/json
      parameters:
        - name: interactionId
          description: 投票id
          required: true
          type: string
          in: path
        - name: userId
          description: 用户id
          required: true
          type: string
          in: path
        - name: body
          description: 投票信息
          required: true
          schema:
            $ref: DoPollForm
          in: body
      responses:
        200:
          description: 成功
          schema:
           $ref: InteractionForm
        default:
          description: error
          schema:
            $ref: Error
  "/interaction/question/{interactionId}/users/{userId}":
    post:
      tags:
        - interaction
      summary: 回答求助
      operationId: poll
      consumes:
        - application/json
      parameters:
        - name: interactionId
          description: 求助id
          required: true
          type: string
          in: path
        - name: userId
          description: 用户id
          required: true
          type: string
          in: path
        - name: body
          description: 求助的评论信息
          required: true
          schema:
            $ref: QuestionCommentForm
          in: body
      responses:
        200:
          description: 成功
          schema:
           $ref: QuestionComment
        default:
          description: error
          schema:
            $ref: Error
definitions:
  Error:
    title: Error
    description: Error
    type: object
    properties:
      msg:
        type: string
  pushInfo:
    title: pushInfo
    type: object
    properties:
      ios_token:
        description: ios的设备token
        type: string
      user_id:
        description: 百度云的userID
        type: string
      channel_id:
        description: 百度云的channelID
        type: string
  LoginForm:
    title: LoginForm
    type: object
    required:
      - email
      - password
      - pushInfo
    properties:
      email:
        description: 用户邮箱
        type: string
      password:
        description: 密码
        type: string
      pushInfo:
        description: "push信息，ios包含ios_token,android包含user_id,channel_id"
        $ref: pushInfo
  GiftResponse:
    title: PostGiftResponse
    type: object
    properties:
      gift:
        type: object
        $ref: Gift
  LoginSuccess:
    title: LoginSuccess
    type: object
    required:
      - token
    properties:
      token:
        type: string
        description: "access token, 有效期7天"
      id:
        type: string
        description: 用户id
  PostGift:
    title: PostGift
    type: object
    required:
     - receiverId
     - gift
     - addition
     - reply_gift
    properties:
      receiverId:
        description: 收礼物人ID
        type: string
        default: 53d79a8e38cf9def07d1ca25
      giftIndex:
        description: 礼物的编号
        type: number
        default: 1
      addition:
        description: 附言
        type: string
      replyGift:
        description: 回复某礼物的Id
        type: string
  Gift:
    title: Gift
    type: object
    required:
      - _id
    properties:
      _id:
        description: giftid
        type: string
  Location:
    title: Location
    required:
      - name
    properties:
      name:
        type: string
        description: 地点名称
      coordinate:
        type: array
        description: 地点坐标
        items:
          type: number
          format: double
  ActivityForm:
    title: ActivityForm
    type: object
    properties:
      target:
        description: 目标id
        type: string
      targetType:
        description: 目标类型
        type: integer
        format: int32
      theme:
        description: 主题
        type: string
      content:
        description: 内容
        type: string
      startTime:
        description: 开始时间
        type: string
        format: date-time
      endTime:
        description: 结束时间
        type: string
        format: date-time
      deadline:
        description: 截止时间
        type: string
        format: date-time
      activityMold:
        description: 活动类型
        type: string
      location:
        $ref: Location
  PollForm:
    title: PollForm
    type: object
    properties:
      target:
        description: 目标id
        type: string
      targetType:
        description: 目标类型
        type: integer
        format: int32
      theme:
        description: 主题
        type: string
      content:
        description: 内容
        type: string
      endTime:
        description: 结束时间
        type: string
        format: date-time
      option:
        description: 选项
        type: array
        items:
          type: string

  QuestionForm:
    title: QuestionForm
    type: object
    properties:
      target:
        description: 目标id
        type: string
      targetType:
        description: 目标类型
        type: integer
        format: int32
      theme:
        description: 主题
        type: string
      content:
        description: 内容
        type: string
      endTime:
        description: 结束时间
        type: string
        format: date-time
  InteractionForm:
    title: InteractionForm
    type: object
    required:
      - target
      - targetType
      - theme
      - content
      - endTime

    properties:
      target:
        description: 目标id
        type: string
      targetType:
        description: 目标类型
        type: integer
        format: int32
        enum:
          - 1
          - 2
          - 3
      theme:
        description: 主题
        type: string
      content:
        description: 内容
        type: string
      endTime:
        description: 结束时间
        type: string
        format: date-time
      startTime:
        description: 开始时间
        type: string
        format: date-time
      deadline:
        description: 截止时间
        type: string
        format: date-time
      activityMold:
        description: 活动类型
        type: string
      loaction:
        $ref: Location
      memberMax:
        description: 最大人数
        type: integer,
        format: int32
      memberMin:
        description: 最小人数
        type: integer
        format: int32
      option:
        description: 选项
        type: array
        items:
          type: string
  Interaction:
    title: Interaction
    type: object
    properties:
      target:
        description: 目标id
        type: string
      targetType:
        description: 目标类型
        type: integer
        format: int32
      theme:
        description: 主题
        type: string
      content:
        description: 内容
        type: string
      endTime:
        description: 结束时间
        type: string
        format: date-time
  DoPollForm:
    title: doPollForm
    type: object
    properties:
      index:
        description: index
        type: integer
        format: int32
  QuestionCommentForm:
    title: answerForm
    type: object
    properties:
      content:
        description: content
        type: string
      type:
        description: 类型，1为评论，2为赞
        type: integer
        format: int32
        enum:
          - 1
          - 2
  QuestionComment:
    title: QuestionComment
    type: object
    properties:
      type:
        description: 类型，1为评论，2为赞
        type: integer
        format: int32
        enum:
          - 1
          - 2
      content:
        description: content
        type: string
      questionId:
        description: questionId
        type: string
      commentId:
        description: 评论一个评论时该评论的id
        type: string
      postCid:
        description: 评论人的公司id
        type: string
      postId:
        description: 评论人的id
        type: string
      createTime:
        description: 创建时间
        type: string
        format: date-time
      status:
        description: 状态//1:正常，2:删除，3:内容删除
        type: integer
        format: int32
        enum:
          - 1
          - 2
          - 3